import React, { useCallback, useEffect, useRef, useState } from 'react'
import { useVP } from '../context/VPContext.jsx'

// GLSL 300 is deliberate: texture() is WebGL2's API, unlike legacy texture2D().
const FRAGMENT = `#version 300 es
precision highp float; uniform sampler2D uSource; uniform vec2 uResolution; uniform float uTime,uExposure,uContrast,uSaturation,uTemperature,uTint,uShadows,uHighlights,uCurve,uEffect,uEffectStrength; out vec4 outColor;
float noise(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);} vec3 grade(vec3 c){c*=exp2(uExposure);c=(c-.5)*max(uContrast,0.)+.5;float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,uSaturation);c+=vec3(uTemperature*.1,uTint*.055,-uTemperature*.1);c+=(1.-l)*uShadows*.24+l*uHighlights*.18;return pow(max(c,0.),vec3(max(.18,uCurve)));}
void main(){vec2 uv=gl_FragCoord.xy/uResolution;uv.y=1.-uv.y;vec2 s=uv;if(uEffect==1.){float w=sin(uv.y*38.+uTime*2.2)*.004+sin(uv.x*22.-uTime*1.5)*.003;s+=vec2(w,sin(uv.x*30.+uTime)*.003)*uEffectStrength;}vec3 c=grade(texture(uSource,clamp(s,.001,.999)).rgb);if(uEffect==2.){vec3 b=vec3(0.);for(int i=-2;i<=2;i++)for(int j=-2;j<=2;j++)b+=texture(uSource,clamp(uv+vec2(float(i),float(j))*.004,.001,.999)).rgb;c+=max(grade(b/25.)-c,0.)*uEffectStrength*1.4;}if(uEffect==3.)c+=(noise(uv*uResolution+uTime)-.5)*.12*uEffectStrength;if(uEffect==4.){float d=.006*uEffectStrength;c.r=grade(texture(uSource,clamp(uv+vec2(d,0.),.001,.999)).rgb).r;c.b=grade(texture(uSource,clamp(uv-vec2(d,0.),.001,.999)).rgb).b;}if(uEffect==5.)c*=1.-smoothstep(.35,.9,length(uv-.5)*1.414)*uEffectStrength*.75;if(uEffect==6.)c=mix(c,floor(c*8.)/8.,uEffectStrength);outColor=vec4(clamp(c,0.,1.),1.);}`
const DEFAULTS={exposure:0,contrast:1,saturation:1,temperature:0,tint:0,shadows:0,highlights:0,curve:1,effectStrength:.5}
const CONTROLS=[['exposure','Exposure',-3,3,.05],['contrast','Contrast',0,2.5,.05],['saturation','Saturation',0,2.5,.05],['temperature','Temperature',-1,1,.05],['tint','Tint',-1,1,.05],['shadows','Shadows',-1,1,.05],['highlights','Highlights',-1,1,.05],['curve','Tone curve',.45,1.8,.02]]
const EFFECTS=[['none','Clean'],['water','Ethereal water'],['bloom','Mist bloom'],['grain','Film grain'],['chroma','Chromatic drift'],['vignette','Vignette'],['posterize','Posterize']]

export default function LightTable(){
 const {vpState,updateVpState,addImportedAssets,toast}=useVP(),[selected,setSelected]=useState(vpState.lightTableAsset||vpState.library?.imported?.[0]||null),[params,setParams]=useState(DEFAULTS),[effect,setEffect]=useState('none'),canvas=useRef(null),image=useRef(new Image()),frame=useRef(0)
 const render=useCallback(()=>{const c=canvas.current,img=image.current;if(!c||!img.naturalWidth)return;const scale=Math.min(1,1400/img.naturalWidth,900/img.naturalHeight);c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const gl=c.getContext('webgl2',{preserveDrawingBuffer:true});if(!gl){c.getContext('2d').drawImage(img,0,0,c.width,c.height);return}const compile=(t,s)=>{const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);return x},v=compile(gl.VERTEX_SHADER,'#version 300 es\\nin vec2 p;void main(){gl_Position=vec4(p,0,1);}'),f=compile(gl.FRAGMENT_SHADER,FRAGMENT);if(!gl.getShaderParameter(f,gl.COMPILE_STATUS)){console.error('Light Table shader error:',gl.getShaderInfoLog(f));return}const p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.useProgram(p);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(p,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const t=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER].forEach(x=>gl.texParameteri(gl.TEXTURE_2D,x,gl.LINEAR));[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T].forEach(x=>gl.texParameteri(gl.TEXTURE_2D,x,gl.CLAMP_TO_EDGE));gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);const u=(n,x)=>gl.uniform1f(gl.getUniformLocation(p,n),x);gl.uniform1i(gl.getUniformLocation(p,'uSource'),0);gl.uniform2f(gl.getUniformLocation(p,'uResolution'),c.width,c.height);u('uTime',performance.now()/1000);Object.entries(params).forEach(([n,x])=>u(`u${n[0].toUpperCase()}${n.slice(1)}`,x));u('uEffect',EFFECTS.findIndex(([id])=>id===effect));gl.viewport(0,0,c.width,c.height);gl.drawArrays(gl.TRIANGLES,0,3)},[params,effect])
 useEffect(()=>{if(!selected)return;image.current.onload=render;image.current.src=selected.src},[selected,render]);useEffect(()=>{render();if(effect==='water'){const tick=()=>{render();frame.current=requestAnimationFrame(tick)};frame.current=requestAnimationFrame(tick)}return()=>cancelAnimationFrame(frame.current)},[render,effect])
 const pick=()=>{const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='image/*';input.onchange=e=>Promise.all([...e.target.files].map(file=>new Promise(done=>{const r=new FileReader();r.onload=x=>done({id:`imported-${Date.now()}-${file.name}`,name:file.name,src:x.target.result,kind:'image',addedAt:new Date().toISOString()});r.readAsDataURL(file)}))).then(assets=>{addImportedAssets(assets);setSelected(assets[0]||null);toast(`${assets.length} image${assets.length===1?'':'s'} added to the library`,'success')});input.click()}
 const save=()=>{if(!canvas.current||!selected)return;const asset={id:`lighttable-${Date.now()}`,name:`${selected.name||'image'} — edited`,src:canvas.current.toDataURL('image/jpeg',.94),kind:'image',addedAt:new Date().toISOString(),recipe:{params,effect}};addImportedAssets([asset]);updateVpState({lightTableAsset:asset});toast('Edited image saved to the shared library','success')}
 return <div className="light-table"><header className="lt-header"><button className="ed-tool" onClick={()=>updateVpState({currentView:vpState.lightTableReturnView||'dashboard',lightTableAsset:null,lightTableReturnView:null})}>← Back</button><div><strong>Light Table</strong><span>Non-destructive grading · shared SVRN library</span></div><div className="lt-header-actions"><button className="ed-tool" onClick={pick}>+ Import to library</button><button className="ed-tool primary" disabled={!selected} onClick={save}>Save edited copy</button></div></header><aside className="lt-library"><div className="lt-section-head"><span>Library</span><button onClick={pick}>+</button></div><div className="lt-thumbs">{(vpState.library?.imported||[]).map(a=><button key={a.id} title={a.name} className={selected?.id===a.id?'active':''} onClick={()=>setSelected(a)}><img src={a.src} alt=""/></button>)}</div>{!(vpState.library?.imported||[]).length&&<p>Import images once, then reuse them everywhere.</p>}</aside><main className="lt-stage">{selected?<><canvas ref={canvas}/><div className="lt-caption">{selected.name}{effect==='water'&&<em> Live ethereal preview</em>}</div></>:<div className="lt-empty"><h2>Your light table is ready.</h2><p>Import a batch of images; they go to the library, never directly onto a page.</p><button className="ed-tool primary" onClick={pick}>Import images</button></div>}</main><aside className="lt-controls"><div className="lt-section-head"><span>Develop</span><button onClick={()=>setParams(DEFAULTS)}>Reset</button></div><section><h4>Color & light</h4>{CONTROLS.map(([key,label,min,max,step])=><label className="lt-control" key={key}><span>{label}<b>{params[key].toFixed(2)}</b></span><input type="range" min={min} max={max} step={step} value={params[key]} onChange={e=>setParams(o=>({...o,[key]:Number(e.target.value)}))}/></label>)}</section><section><h4>Ethereal effects</h4><div className="lt-effects">{EFFECTS.map(([id,label])=><button key={id} className={effect===id?'active':''} onClick={()=>setEffect(id)}>{label}</button>)}</div>{effect!=='none'&&<label className="lt-control"><span>Intensity<b>{params.effectStrength.toFixed(2)}</b></span><input type="range" min="0" max="1" step=".05" value={params.effectStrength} onChange={e=>setParams(o=>({...o,effectStrength:Number(e.target.value)}))}/></label>}</section></aside></div>
}
